#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/util/simpleopt'

$0 = "rbbt #{$previous_commands*" "} #{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF

Bootstrap InterPro resources

$ #{$0} [options] <filename.tsv|->

Use - to read from STDIN

-h--help Print this help

EOF
if options[:help]
  if defined? rbbt_usage
    rbbt_usage 
  else
    puts SOPT.doc
  end
  exit 0
end

require 'rbbt/workflow'
Workflow.require_workflow "InterPro"

Log.with_severity 0 do
  %w(Hsa Mmu Rno).each do |organism|
    codes = Organism.organism_codes(organism)
    codes.each do |code|
      Log.tsv InterPro[code].protein_domains.tsv
    end
  end
end
